Lowered chi2 value test in system test Relax_disp.test_bug_22146_unpacking_r2a_r2b_cluster_NS_STAR.
This is due to the data produced on 32 bit machine, and tested on 64 bit machines.
The error was:
AssertionError: 2.4659455670347743e-05 != 0.0 within 7 places

The reason for this is due to truncation artifacts.

git-svn-id: svn+ssh://svn.gna.org/svn/relax/trunk@23784 b7916896-f9f9-0310-9fe5-b3996d8957d5